### ISSUE TITLE
Consider pull requests on original repo

### ISSUE THREAD

**Issue by ronaldtse** [fontist/seven_zip_ruby#6]
Will this be useful?

* https://github.com/masamitsu-murase/seven_zip_ruby/pull/26

**Comment by maxirmx** [comment]
> Will this be useful?
> 
> * [* Result block value for SevenZipReader.open & .open_file masamitsu-murase/seven_zip_ruby#26](https://github.com/masamitsu-murase/seven_zip_ruby/pull/26)

No, I do not think it can be useful in excavate
